# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_thumbnail',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
            preserve_default=False,
        ),
    ]
