# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0002_category_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='short_description',
            field=models.CharField(default='foo', max_length=50),
            preserve_default=False,
        ),
    ]
