# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiques', '0003_type_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='short_description',
        ),
    ]
